# A failed attempt at building a GUI for this.
# source generated by foxGUIb 1.0.0

require './interwiki_conflicts'

class StreamFoxWriter < IO
	def initialize target
		@target = target
	end
	
	def write *a
		a.each{|b| @target.appendText b}
	end
end

class MainWindow
	def initialize( parent)
		@groups = []
		@lists = []
		construct_widget_tree( parent)
		init if respond_to? 'init'
	end
	
	def construct_widget_tree( parent)
		@topwin=
		FX::MainWindow.new(parent){|w|
			@mainWindow=w
			w.wdg_name='mainWindow'
			w.shown=true
			w.x=450
			w.y=310
			w.width=500
			w.height=400
			FX::VerticalFrame.new(@mainWindow){|w|
				@rootframe=w
				w.wdg_name='rootframe'
				w.width=500
				w.height=400
				FX::HorizontalFrame.new(@rootframe){|w|
					@topframe=w
					w.wdg_name='topframe'
					w.layoutHints=1536
					w.width=500
					w.height=26
					FX::Button.new(@topframe){|w|
						@addbutton=w
						w.wdg_name='addbutton'
						w.layoutHints=772
						w.x=450
						w.width=50
						w.height=25
						w.text="Add..."
					}
					FX::Button.new(@topframe){|w|
						@gatherbutton=w
						w.wdg_name='gatherbutton'
						w.layoutHints=772
						w.x=450
						w.width=60
						w.height=25
						w.text="Gather..."
					}
					FX::Button.new(@topframe){|w|
						@moveselbutton=w
						w.wdg_name='moveselbutton'
						w.layoutHints=772
						w.x=450
						w.width=80
						w.height=25
						w.text="Move selected..."
					}
					FX::Label.new(@topframe){|w|
						@titletext=w
						w.wdg_name='titletext'
						w.layoutHints=1024
						w.justify=32768
						w.width=450
						w.height=17
						w.text="InterwikiConflictSolver"
					}
				}
				FX::Text.new(@rootframe){|w|
					@log=w
					w.wdg_name='log'
					w.layoutHints=1553
					w.y=368
					w.width=500
					w.height=50
				}
				FX::HorizontalFrame.new(@rootframe){|w|
					@bottomframe=w
					w.wdg_name='bottomframe'
					w.layoutHints=1553
					w.y=368
					w.width=500
					w.height=32
					FX::Button.new(@bottomframe){|w|
						@commitbutton=w
						w.wdg_name='commitbutton'
						w.layoutHints=772
						w.x=430
						w.width=70
						w.height=30
						w.text="Commit"
					}
					FX::Label.new(@bottomframe){|w|
						@summarylabel=w
						w.wdg_name='summarylabel'
						w.width=55
						w.height=17
						w.text="Summary: "
					}
					FX::TextField.new(@bottomframe){|w|
						@summaryfield=w
						w.wdg_name='summaryfield'
						w.layoutHints=1024
						w.x=55
						w.width=375
						w.height=19
					}
				}
				FX::HorizontalFrame.new(@rootframe){|w|
					@middleframe=w
					w.wdg_name='middleframe'
					w.y=26
					w.width=500
					w.height=342
				}
			}
		}
	end
	
	def add_group name=nil
		FX::GroupBox.new(@middleframe){|w|
			@groups << w
			w.wdg_name="group#{@groups.length}"
			w.layoutHints=3072
			w.width=250
			w.height=342
			w.text=name || ask("Group name?") || "Group #{@groups.length}"
			FX::List.new(@groups.last){|w|
				@lists << w
				w.wdg_name="list#{@groups.length}"
				w.x=6
				w.y=21
				w.width=238
				w.height=315
			}
		}.create
		@mainWindow.recalc
		
		last_list = @lists.last
		
		last_list.connect(Fox::SEL_RIGHTBUTTONRELEASE){move_selected_to last_list}
		last_list.connect(Fox::SEL_LEFTBUTTONRELEASE){move_selected_to last_list if @moving_now; @moving_now=false}
		
		last_list.connect(Fox::SEL_DOUBLECLICKED){|i|
			Thread.new do
			wiki, title = * last_list.getItem(i).to_s.split(':', 2)
			Launchy.open "http://#{wiki}.wikipedia.org/w/index.php?title=#{CGI.escape title}"
		end }
	end
	
	def do_gather
		art = ask "Article to gather from, in format lng:Article title:", 'Gather'
		wiki, title = *art.split(':', 2)
		
		# p eval gets while $_ != "\n"
		
		old_gs = @iw.groups.values.uniq
		@iw.gather_from wiki, title, false
		new_key = (@iw.groups.values.uniq - old_gs)[0]
		
		if new_key
			add_group new_key.to_s
			@iw.groups.each_pair do |(wiki, art), group|
				item = Fox::FXListItem.new "#{wiki}:#{art}"
				@groups.each_with_index do |g, i|
					if g.inspect == group
						@lists[i] << item
						break
					end
				end
			end
		end
		
	rescue
		p $!
		puts $!.backtrace
	end
	
	def ask question, title=question
		Fox::FXInputDialog.getString '', @mainWindow, title, question
	end
	
	def move_selected_to target_list
		@lists.each do |list|
			i = 0
			while i < list.numItems
				item = list.getItem i
				if item.selected?
					target_list.appendItem item.to_s
					list.removeItem i
				else
					i += 1
				end
			end
		end
	end
	
	def init
		@iw = InterwikiConflictSolver.new
		
		@addbutton.connect(Fox::SEL_COMMAND){add_group}
		@gatherbutton.connect(Fox::SEL_COMMAND){do_gather}
		@moveselbutton.connect(Fox::SEL_COMMAND){@moving_now = !@moving_now}
		
		$stdout = $stderr = StreamFoxWriter.new @log
	end
	
	attr_reader :topwin
	attr_reader :mainWindow
	attr_reader :rootframe
	attr_reader :topframe
	attr_reader :addbutton
	attr_reader :titletext
	attr_reader :bottomframe
	attr_reader :commitbutton
	attr_reader :summarylabel
	attr_reader :summaryfield
	attr_reader :middleframe
	attr_reader :groups
	attr_reader :lists
end

#unit test
if __FILE__==$0
	require 'libGUIb16'
	app=FX::App.new
	w=MainWindow.new app
	w.topwin.show(Fox::PLACEMENT_SCREEN)
	app.create
	app.run
end
